---
title: PdfException
second_title: Aspose.PDF for .NET API 参考
description: 初始化PdfExceptionaspose.pdf/pdfexception类的新实例
type: docs
weight: 10
url: /zh/net/aspose.pdf/pdfexception/pdfexception/
---
## PdfException() {#constructor}

初始化[`PdfException`](../../pdfexception)类的新实例。

```csharp
public PdfException()
```

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(string) {#constructor_2}

初始化[`PdfException`](../../pdfexception)类的新实例。

```csharp
public PdfException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 消息。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(string, Exception) {#constructor_3}

使用指定的错误消息初始化[`PdfException`](../../pdfexception) 类的新实例以及对导致此异常的内部异常的引用。

```csharp
public PdfException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常，如果未指定内部异常，则为空引用（Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(Exception) {#constructor_1}

使用指定的错误消息初始化[`PdfException`](../../pdfexception) 类的新实例以及对导致此异常的内部异常的引用。

```csharp
public PdfException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 导致当前异常的异常，如果没有内部异常，则为空引用（在 Visual Basic 中为空）被指定。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.PDF.dll -->
