---
title: PdfException
second_title: Aspose.PDF for .NET API 参考
description: 初始化PdfExceptionaspose.pdf/pdfexception类.
type: docs
weight: 10
url: /zh/net/aspose.pdf/pdfexception/pdfexception/
---
## PdfException() {#constructor}

初始化[`PdfException`](../../pdfexception)类.

```csharp
public PdfException()
```

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(string) {#constructor_2}

初始化[`PdfException`](../../pdfexception)类.

```csharp
public PdfException(string message)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 消息。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(string, Exception) {#constructor_3}

初始化[`PdfException`](../../pdfexception)具有指定错误消息的类和对导致此异常的内部异常的引用。

```csharp
public PdfException(string message, Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| message | String | 解释异常原因的错误消息。 |
| innerException | Exception | 导致当前异常的异常，如果未指定内部异常，则为空引用（Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

---

## PdfException(Exception) {#constructor_1}

初始化[`PdfException`](../../pdfexception)具有指定错误消息的类和对导致此异常的内部异常的引用。

```csharp
public PdfException(Exception innerException)
```

| 范围 | 类型 | 描述 |
| --- | --- | --- |
| innerException | Exception | 导致当前异常的异常，如果未指定内部异常，则为空引用（Visual Basic 中为 Nothing）。 |

### 也可以看看

* class [PdfException](../../pdfexception)
* 命名空间 [Aspose.Pdf](../../pdfexception)
* 部件 [Aspose.PDF](../../../)

<!-- DO NOT EDIT: generated by xmldocmd for Aspose.PDF.dll -->
