---
title: PdfException.PdfException
second_title: Aspose.PDF for .NET API Reference
description: PdfException コンストラクタ。PdfException クラスの新しいインスタンスを初期化します
type: docs
weight: 10
url: /ja/net/aspose.pdf/pdfexception/pdfexception/
---
## PdfException() {#constructor}

[`PdfException`](../) クラスの新しいインスタンスを初期化します。

```csharp
public PdfException()
```

### 関連項目

* クラス [PdfException](../)
* 名前空間 [Aspose.Pdf](../../../aspose.pdf/)
* アセンブリ [Aspose.PDF](../../../)

---

## PdfException(string) {#constructor_2}

[`PdfException`](../) クラスの新しいインスタンスを初期化します。

```csharp
public PdfException(string message)
```

| パラメーター | 型 | 説明 |
| --- | --- | --- |
| message | String | メッセージ。 |

### 関連項目

* クラス [PdfException](../)
* 名前空間 [Aspose.Pdf](../../../aspose.pdf/)
* アセンブリ [Aspose.PDF](../../../)

---

## PdfException(string, Exception) {#constructor_3}

指定されたエラーメッセージと、この例外の原因となる内部例外への参照を持つ [`PdfException`](../) クラスの新しいインスタンスを初期化します。

```csharp
public PdfException(string message, Exception innerException)
```

| パラメーター | 型 | 説明 |
| --- | --- | --- |
| message | String | 例外の理由を説明するエラーメッセージ。 |
| innerException | Exception | 現在の例外の原因となる例外、または内部例外が指定されていない場合は null 参照 (Visual Basic では Nothing) 。 |

### 関連項目

* クラス [PdfException](../)
* 名前空間 [Aspose.Pdf](../../../aspose.pdf/)
* アセンブリ [Aspose.PDF](../../../)

---

## PdfException(Exception) {#constructor_1}

この例外の原因となる内部例外への参照を持つ [`PdfException`](../) クラスの新しいインスタンスを初期化します。

```csharp
public PdfException(Exception innerException)
```

| パラメーター | 型 | 説明 |
| --- | --- | --- |
| innerException | Exception | 現在の例外の原因となる例外、または内部例外が指定されていない場合は null 参照 (Visual Basic では Nothing) 。 |

### 関連項目

* クラス [PdfException](../)
* 名前空間 [Aspose.Pdf](../../../aspose.pdf/)
* アセンブリ [Aspose.PDF](../../../)