---
title: PdfException.PdfException
second_title: Aspose.PDF for .NET API Reference
description: مُنشئ PdfException. يُهيئ مثيلًا جديدًا من فئة PdfException
type: docs
weight: 10
url: /ar/net/aspose.pdf/pdfexception/pdfexception/
---
## PdfException() {#constructor}

يُهيئ مثيلًا جديدًا من فئة [`PdfException`](../).

```csharp
public PdfException()
```

### انظر أيضًا

* فئة [PdfException](../)
* مساحة الأسماء [Aspose.Pdf](../../../aspose.pdf/)
* التجميع [Aspose.PDF](../../../)

---

## PdfException(string) {#constructor_2}

يُهيئ مثيلًا جديدًا من فئة [`PdfException`](../).

```csharp
public PdfException(string message)
```

| المعامل | النوع | الوصف |
| --- | --- | --- |
| message | String | الرسالة. |

### انظر أيضًا

* فئة [PdfException](../)
* مساحة الأسماء [Aspose.Pdf](../../../aspose.pdf/)
* التجميع [Aspose.PDF](../../../)

---

## PdfException(string, Exception) {#constructor_3}

يُهيئ مثيلًا جديدًا من فئة [`PdfException`](../) مع رسالة خطأ محددة ومرجع إلى الاستثناء الداخلي الذي هو سبب هذا الاستثناء.

```csharp
public PdfException(string message, Exception innerException)
```

| المعامل | النوع | الوصف |
| --- | --- | --- |
| message | String | رسالة الخطأ التي تشرح سبب الاستثناء. |
| innerException | Exception | الاستثناء الذي هو سبب الاستثناء الحالي، أو مرجع فارغ (Nothing في Visual Basic) إذا لم يتم تحديد استثناء داخلي. |

### انظر أيضًا

* فئة [PdfException](../)
* مساحة الأسماء [Aspose.Pdf](../../../aspose.pdf/)
* التجميع [Aspose.PDF](../../../)

---

## PdfException(Exception) {#constructor_1}

يُهيئ مثيلًا جديدًا من فئة [`PdfException`](../) مع مرجع إلى الاستثناء الداخلي الذي هو سبب هذا الاستثناء.

```csharp
public PdfException(Exception innerException)
```

| المعامل | النوع | الوصف |
| --- | --- | --- |
| innerException | Exception | الاستثناء الذي هو سبب الاستثناء الحالي، أو مرجع فارغ (Nothing في Visual Basic) إذا لم يتم تحديد استثناء داخلي. |

### انظر أيضًا

* فئة [PdfException](../)
* مساحة الأسماء [Aspose.Pdf](../../../aspose.pdf/)
* التجميع [Aspose.PDF](../../../)